title: VyrxAI
description: Finish homework instantly

# remove file extensions
permalink: pretty

# dont process
exclude:
  - README.md
  - LICENSE.md
  - LICENSE
  - config.js
  - testimonials.js
  - videos/READTHIS.md
